### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by joshlemer** [ProjectAton/AtonLab#63]
It seems that the project website linked in the repository (http://camilosampedro.me/Aton) doesn't point anywhere.

**Comment by mgochoa** [comment]
DNS is down, because it was a tier free one. While the owner changes the description, you can use this link [http://camilosampedro.github.io/Aton](http://camilosampedro.github.io/Aton)

**Comment by camilosampedro** [comment]
I need to update it! Thank you for reporting it.
